env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - PROJECT_NAME=fs-automation
  - PROJECT_USER=incu6us

before:
  hooks:
    - go mod download

builds:
  - id: fs-automation-amd64
    binary: fs-automation
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    maintainer: Vyacheslav Pryimak <vyacheslavpryimak@gmail.com>
    description: |-
      Actions on files/directories events
    vendor: Vyacheslav Pryimak
    homepage: https://github.com/incu6us/fs-automation
    license: MIT
    bindir: /usr/bin
    section: utils
    contents:
      - src: config.yaml
        dst: /etc/fs-automation/config.yaml
        type: config
      - src: systemd/fs-automation.service
        dst: /etc/systemd/system/fs-automation.service
        type: config
    formats:
      - deb
      - rpm

#release:
#  prerelease: auto
#  github:
#    owner: incu6us
#    name: fs-automation

snapcrafts:
  - id: fs-automation
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    publish: true
    summary: "Actions on files/directories events"
    description: |
      Actions on files/directories events
    grade: stable
    confinement: strict
    license: MIT
    extra_files:
      - source: config.yaml
        destination: etc/fs-automation/config.yaml
        mode: 0644
    layout:
      /etc/fs-automation:
        bind: $SNAP/etc/fs-automation
    apps:
      fs-automation:
        args: start --cfg /etc/fs-automation/config.yaml
        daemon: simple
        stop_mode: sigterm
