name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -race -v -cover -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Build
      run: go build -v ./...

    - name: Create deb package
      uses: skynet-core/nfpm@v1.5
      id: deb-package
      with:
        config: "nfpm.yaml"
        packager: "deb"

    - name: Create rpm package
      uses: skynet-core/nfpm@v1.5
      id: rpm-package
      with:
        config: "nfpm.yaml"
        packager: "rpm"
